-- 创建验证码表
CREATE TABLE IF NOT EXISTS verification_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  code VARCHAR(6) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiry_time TIMESTAMP NOT NULL,
  is_used BOOLEAN DEFAULT FALSE,
  INDEX email_idx (email)
); 